name: data_sys
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: "^3.3.4"

dependencies:
  flutter:
    sdk: flutter
  path:
  sqflite:
  sqflite_common_ffi:
  flutter_typeahead: ^3.2.7
  intl: ^0.19.0
  flutter_native_splash:
  dynamic_color: ^1.7.0
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/VSCode.png
